In [8]:
#importing libraries
import tensorflow as tf

#### Vocabulary

In [19]:
#without include_special_token option
sentences= ['I love my dog', 'I love my cat','you love my dog!']

vectorize_layer = tf.keras.layers.TextVectorization()
vectorize_layer.adapt(sentences)
vocab = vectorize_layer.get_vocabulary()
for i, word in enumerate(vocab):
    print(i,word)

0 
1 [UNK]
2 my
3 love
4 i
5 dog
6 you
7 cat


In [7]:
#with include_special_token

vectorize_layer = tf.keras.layers.TextVectorization()
vectorize_layer.adapt(sentences)

vocabulary = vectorize_layer.get_vocabulary(include_special_tokens=False)
for inx, word in enumerate(vocabulary) :
    print(inx, word)

0 my
1 love
2 i
3 dog
4 you
5 cat


The resulting vocabulary will be a list where more frequently used words will have a lower index. 

#### Text to Sequence

In [11]:
sequence = vectorize_layer("I love my dog")
sequence

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([4, 3, 2, 5])>

In [20]:
sentences.extend(["I'm in love my your dog, its amazing"])
sentences

['I love my dog',
 'I love my cat',
 'you love my dog!',
 "I'm in love my your dog, its amazing"]

In [24]:
#let's apply on list of sentences and check sequences
sequences = vectorize_layer(sentences)
sequences

#by default it is doing post padding, based on the length of largest sentence

<tf.Tensor: shape=(4, 8), dtype=int64, numpy=
array([[4, 3, 2, 5, 0, 0, 0, 0],
       [4, 3, 2, 7, 0, 0, 0, 0],
       [6, 3, 2, 5, 0, 0, 0, 0],
       [1, 1, 3, 2, 1, 5, 1, 1]])>